"""Generate TypeScript schema aliases from our OpenAPI 3.1 schema subset."""
import json
import sys
from pathlib import Path
import yaml
ROOT = Path(__file__).resolve().parents[1]
def ts(s):
    if not s: return 'unknown'
    if '$ref' in s: return s['$ref'].rsplit('/', 1)[1]
    if 'const' in s: return json.dumps(s['const'])
    if 'enum' in s: return ' | '.join(json.dumps(v) for v in s['enum'])
    for key, separator in [('oneOf',' | '),('anyOf',' | '),('allOf',' & ')]:
        if key in s:
            base = {k:v for k,v in s.items() if k != key}
            combined = '(' + separator.join(ts(v) for v in s[key]) + ')'
            return ts(base) + ' & ' + combined if 'properties' in base else combined
    kind=s.get('type')
    if isinstance(kind,list): return ' | '.join(ts(dict(s,type=k)) for k in kind)
    if kind=='array': return '('+ts(s['items'])+')[]'
    if kind=='object' or 'properties' in s:
        required=s.get('required',[])
        return '{ '+ '; '.join(json.dumps(k)+('' if k in required else '?')+': '+ts(v) for k,v in s.get('properties',{}).items())+' }'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')
schemas=yaml.safe_load((ROOT/'api/openapi.yaml').read_text())['components']['schemas']
output='// Generated by scripts/generate_frontend_types.py; do not edit.\n'
output+='\n'.join('export type '+name+' = '+ts(schema)+';' for name,schema in schemas.items())+'\n'
target=ROOT/'frontend/src/shared/api/generated.ts'
if '--check' in sys.argv:
    if not target.exists() or target.read_text()!=output:
        raise SystemExit('Frontend types are stale: run make generate-frontend-types')
else:
    target.write_text(output)
